# Generated by Django 3.0.5 on 2020-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(default=0)),
                ('city', models.CharField(default='none', max_length=30)),
                ('state', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
